import {
  ApartmentOutlined, AuditOutlined, BookOutlined, CheckCircleOutlined, CloseCircleOutlined, DownloadOutlined,
  FileExcelOutlined, FileTextOutlined, LockOutlined, PlusOutlined, ReloadOutlined, SafetyCertificateOutlined,
  UnlockOutlined,
} from '@ant-design/icons';
import { Alert, Button, Card, DatePicker, Empty, Form, Input, InputNumber, Modal, Popconfirm, Select, Space, Statistic, Table, Tabs, Tag, Upload, message } from 'antd';
import dayjs, { Dayjs } from 'dayjs';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { ApiError, request } from '../lib/api';
import { auth } from '../lib/auth';

type Account = { id:number; code:string; name:string; level:number; parentId:number|null; category:string; balanceDirection:'debit'|'credit'; isSystem:boolean; allowPosting:boolean; isActive:boolean };
type AccountSet = { name:string; accountingStandard:string; taxJurisdiction:string; reportingProfile:string; taxFilingFrequency:string; requiredReports:string[]; currentPeriod:string; closedThrough:string|null };
type VoucherLine = { id?:number; accountId:number; summary:string; debit:string|number; credit:string|number; counterpartyName?:string|null; account?:Account };
type Voucher = { id:number; voucherNo:string; voucherDate:string; period:string; summary:string; status:'draft'|'reviewed'|'posted'|'void'; sourceType?:string|null; totalDebit:string; totalCredit:string; revision:number; lines:VoucherLine[] };
type LedgerRow = { account:Account; openingDebit:string; openingCredit:string; debit:string; credit:string; closingDebit:string; closingCredit:string };
type LedgerEntry = { id:number; lineNo:number; summary:string; debit:string; credit:string; projectName?:string|null; counterpartyName?:string|null; account:Account; voucher:{voucherNo:string;voucherDate:string} };
type Reports = { period:string; balanceSheet:{assets:number;liabilities:number;equity:number;liabilitiesAndEquity:number;balanced:boolean}; profitStatement:{operatingRevenue:number;operatingCosts:number;netProfit:number}; traceable:boolean; cashFlowReconciled:null|boolean };
type Overview = { accountSet:AccountSet; accounts:Account[]; voucherCounts:{draft:number;reviewed:number;posted:number}; periods:Array<{period:string;status:string;closedAt?:string}> };

const categoryLabels:Record<string,string>={asset:'资产',liability:'负债',equity:'所有者权益',cost:'成本',profit_loss:'损益'};
const statusLabels:Record<string,[string,string]>={draft:['待复核','orange'],reviewed:['待过账','blue'],posted:['已过账','green'],void:['已作废','default']};
const money=(v:unknown)=>Number(v||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const errorText=(e:unknown)=>e instanceof ApiError||e instanceof Error?e.message:'操作失败，请稍后重试';

export default function FinanceAccountingCenter(){
  const [period,setPeriod]=useState(dayjs().format('YYYY-MM')); const [loading,setLoading]=useState(true);
  const [overview,setOverview]=useState<Overview|null>(null); const [vouchers,setVouchers]=useState<Voucher[]>([]);
  const [ledger,setLedger]=useState<{rows:LedgerRow[];validation:{debit:number;credit:number}}|null>(null); const [reports,setReports]=useState<Reports|null>(null);
  const [ledgerDetail,setLedgerDetail]=useState<{entries:LedgerEntry[];projectSummary:Array<{name:string;debit:number;credit:number;entries:number}>;counterpartySummary:Array<{name:string;debit:number;credit:number;entries:number}>}|null>(null);
  const [opening,setOpening]=useState<any>(null); const [accountOpen,setAccountOpen]=useState(false); const [voucherOpen,setVoucherOpen]=useState(false);
  const [editing,setEditing]=useState<Voucher|null>(null); const [history,setHistory]=useState<any[]|null>(null); const [accountForm]=Form.useForm(); const [voucherForm]=Form.useForm();

  const load=useCallback(async()=>{
    setLoading(true);
    try{
      const [o,v,l,ld,r,b]=await Promise.all([
        request({url:`/finance/accounting/overview?period=${period}`}),request({url:`/finance/accounting/vouchers?period=${period}`}),
        request({url:`/finance/accounting/ledger?period=${period}`}),request({url:`/finance/accounting/ledger-entries?period=${period}`}),request({url:`/finance/accounting/reports?period=${period}`}),
        request({url:`/finance/accounting/opening-balances?period=${period}`}),
      ]);
      setOverview(o as Overview);setVouchers(v as Voucher[]);setLedger(l as any);setLedgerDetail(ld as any);setReports(r as Reports);setOpening(b);
    }catch(e){message.error(errorText(e));}finally{setLoading(false);}
  },[period]);
  useEffect(()=>{void load()},[load]);
  const accounts=overview?.accounts||[]; const postingAccounts=useMemo(()=>accounts.filter(a=>a.allowPosting&&a.isActive),[accounts]);
  const periodClosed=overview?.periods.some(p=>p.period===period&&p.status==='closed');

  const downloadTemplate=async()=>{try{const response=await fetch(`${import.meta.env.VITE_API_BASE_URL||'/api/v1'}/finance/accounting/opening-template`,{headers:{Authorization:`Bearer ${auth.getToken()}`}});if(!response.ok)throw new Error('模板下载失败');const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='小企业会计准则-期初余额模板.xlsx';link.click();URL.revokeObjectURL(url);}catch(e){message.error(errorText(e));}};
  const downloadReports=async()=>{try{const response=await fetch(`${import.meta.env.VITE_API_BASE_URL||'/api/v1'}/finance/accounting/reports/export?period=${period}`,{headers:{Authorization:`Bearer ${auth.getToken()}`}});if(!response.ok)throw new Error('报表导出失败');const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`上海小企业财务报表-${period}.xlsx`;link.click();URL.revokeObjectURL(url);}catch(e){message.error(errorText(e));}};
  const importOpening=async(file:File)=>{try{const form=new FormData();form.append('file',file);const response=await fetch(`${import.meta.env.VITE_API_BASE_URL||'/api/v1'}/finance/accounting/opening-import?period=${period}`,{method:'POST',headers:{Authorization:`Bearer ${auth.getToken()}`},body:form});const body=await response.json();if(!response.ok)throw new Error(body?.message||'导入失败');if(body.batch?.status==='invalid'){Modal.error({title:'期初余额没有导入',width:620,content:<div><p>请修正以下问题后重新导入：</p>{(body.batch.errors||[]).map((x:string)=><Alert key={x} type="error" showIcon message={x} className="accounting-import-error"/>)}</div>});}else{message.success(`已导入 ${body.batch.importedRows} 个科目的期初余额`);await load();}}catch(e){message.error(errorText(e));}};

  const createAccount=async(values:any)=>{try{await request({method:'POST',url:'/finance/accounting/accounts',data:values});message.success('明细科目已新增');setAccountOpen(false);accountForm.resetFields();await load();}catch(e){message.error(errorText(e));}};
  const openVoucher=(voucher?:Voucher)=>{setEditing(voucher||null);voucherForm.setFieldsValue(voucher?{voucherDate:dayjs(voucher.voucherDate),summary:voucher.summary,lines:voucher.lines.map(l=>({accountId:l.accountId,summary:l.summary,counterpartyName:l.counterpartyName,debit:Number(l.debit)||undefined,credit:Number(l.credit)||undefined}))}:{voucherDate:dayjs(),summary:'',lines:[{summary:'',debit:undefined,credit:undefined},{summary:'',debit:undefined,credit:undefined}]});setVoucherOpen(true)};
  const saveVoucher=async(values:any)=>{try{const data={...values,voucherDate:values.voucherDate.format('YYYY-MM-DD')};await request({method:editing?'PUT':'POST',url:editing?`/finance/accounting/vouchers/${editing.id}`:'/finance/accounting/vouchers',data});message.success(editing?'凭证修改已记录':'凭证已创建');setVoucherOpen(false);await load();}catch(e){message.error(errorText(e));}};
  const changeStatus=async(voucher:Voucher,action:'review'|'post'|'unpost')=>{try{await request({method:'POST',url:`/finance/accounting/vouchers/${voucher.id}/status`,data:{action}});message.success(action==='review'?'复核完成':action==='post'?'过账完成':'已取消过账');await load();}catch(e){message.error(errorText(e));}};
  const showHistory=async(voucher:Voucher)=>{try{setHistory(await request({url:`/finance/accounting/vouchers/${voucher.id}/history`}) as any[]);}catch(e){message.error(errorText(e));}};
  const closePeriod=async(reverse=false)=>{try{await request({method:'POST',url:`/finance/accounting/periods/${period}/${reverse?'reverse':'close'}`});message.success(reverse?'已反结账，相关操作已记录':'本期已结账');await load();}catch(e){message.error(errorText(e));}};
  const generateProfitClosing=async()=>{try{await request({method:'POST',url:`/finance/accounting/periods/${period}/profit-closing`});message.success('损益结转草稿凭证已生成，请复核后过账');await load();}catch(e){message.error(errorText(e));}};
  const syncSources=async()=>{try{const result:any=await request({method:'POST',url:'/finance/accounting/sources/sync'});message.success(`同步完成：新增 ${result.created} 张草稿凭证，跳过 ${result.skipped} 张已同步单据`);await load();}catch(e){message.error(errorText(e));}};

  const voucherColumns=[
    {title:'凭证号',dataIndex:'voucherNo',width:110,render:(v:string,r:Voucher)=><button className="accounting-link" onClick={()=>openVoucher(r)}>{v}</button>},
    {title:'日期',dataIndex:'voucherDate',width:120},{title:'摘要',dataIndex:'summary',minWidth:240},{title:'来源',dataIndex:'sourceType',width:100,render:(v:string)=>v==='entry'?<Tag color="cyan">流水自动生成</Tag>:<Tag>人工</Tag>},
    {title:'借方',dataIndex:'totalDebit',align:'right' as const,width:130,render:(v:string)=><span className="accounting-number">¥{money(v)}</span>},{title:'贷方',dataIndex:'totalCredit',align:'right' as const,width:130,render:(v:string)=><span className="accounting-number">¥{money(v)}</span>},
    {title:'状态',dataIndex:'status',width:100,render:(v:string)=>{const x=statusLabels[v]||[v,'default'];return <Tag color={x[1]}>{x[0]}</Tag>}},
    {title:'操作',fixed:'right' as const,width:230,render:(_:unknown,r:Voucher)=><Space>{r.status==='draft'&&<Button size="small" onClick={()=>changeStatus(r,'review')}>复核</Button>}{r.status==='reviewed'&&<Button size="small" type="primary" onClick={()=>changeStatus(r,'post')}>过账</Button>}{r.status==='posted'&&<Button size="small" disabled={periodClosed} onClick={()=>changeStatus(r,'unpost')}>取消过账</Button>}<Button size="small" onClick={()=>showHistory(r)}>记录</Button></Space>},
  ];
  const ledgerColumns=[{title:'科目编码',dataIndex:['account','code'],width:120},{title:'科目名称',dataIndex:['account','name'],minWidth:180},{title:'期初借',dataIndex:'openingDebit',align:'right' as const,render:money},{title:'期初贷',dataIndex:'openingCredit',align:'right' as const,render:money},{title:'本期借',dataIndex:'debit',align:'right' as const,render:money},{title:'本期贷',dataIndex:'credit',align:'right' as const,render:money},{title:'期末借',dataIndex:'closingDebit',align:'right' as const,render:money},{title:'期末贷',dataIndex:'closingCredit',align:'right' as const,render:money}];

  return <div className="accounting-center">
    <div className="accounting-toolbar"><div><span className="accounting-kicker"><SafetyCertificateOutlined/> 上海 · 小企业会计准则</span><h2>会计工作台</h2><p>{overview?.accountSet.name||'正在初始化账套'} · 人民币本位币 · 报表可追溯到凭证和原始单据</p></div><Space wrap><DatePicker picker="month" allowClear={false} value={dayjs(period)} onChange={(v:Dayjs|null)=>v&&setPeriod(v.format('YYYY-MM'))}/><Button icon={<ReloadOutlined/>} onClick={load}>刷新</Button></Space></div>
    <div className="accounting-status-strip"><div><span>账期状态</span><strong className={periodClosed?'closed':'open'}>{periodClosed?<><LockOutlined/> 已结账</>:<><UnlockOutlined/> 可记账</>}</strong></div><div><span>待复核</span><b>{overview?.voucherCounts.draft||0}</b></div><div><span>待过账</span><b>{overview?.voucherCounts.reviewed||0}</b></div><div><span>已过账</span><b>{overview?.voucherCounts.posted||0}</b></div></div>
    <Tabs className="accounting-tabs" items={[
      {key:'accounts',label:<span><ApartmentOutlined/> 会计科目</span>,children:<Card className="accounting-card" title="标准科目表" extra={<Button type="primary" icon={<PlusOutlined/>} onClick={()=>setAccountOpen(true)}>新增明细科目</Button>}><Alert showIcon type="info" message="一级科目由系统保护" description="已内置《小企业会计准则》一级科目与报表映射。可在一级或现有明细科目下继续增加明细；存在明细时，上级科目自动停止直接记账。"/><Table loading={loading} rowKey="id" pagination={{pageSize:20}} scroll={{x:760}} dataSource={accounts} columns={[{title:'编码',dataIndex:'code',width:130},{title:'科目名称',dataIndex:'name',render:(v:string,r:Account)=><span style={{paddingLeft:(r.level-1)*18}}>{v}</span>},{title:'类别',dataIndex:'category',render:(v:string)=><Tag>{categoryLabels[v]}</Tag>},{title:'余额方向',dataIndex:'balanceDirection',render:(v:string)=>v==='debit'?'借':'贷'},{title:'级次',dataIndex:'level'},{title:'属性',render:(_:unknown,r:Account)=><Space>{r.isSystem&&<Tag color="blue">标准一级科目</Tag>}{!r.allowPosting&&<Tag>汇总科目</Tag>}</Space>}]} /></Card>},
      {key:'opening',label:<span><FileExcelOutlined/> 期初余额</span>,children:<Card className="accounting-card" title={`${period} 期初余额`} extra={<Space wrap><Button icon={<DownloadOutlined/>} onClick={downloadTemplate}>下载模板</Button><Upload accept=".xlsx,.xls" showUploadList={false} disabled={periodClosed} customRequest={({file,onSuccess,onError})=>{importOpening(file as File).then(()=>onSuccess?.({})).catch(e=>onError?.(e))}}><Button type="primary" icon={<FileExcelOutlined/>} disabled={periodClosed}>导入 Excel</Button></Upload></Space>}><div className="validation-grid"><Alert showIcon type={opening?.validation?.balanced?'success':'warning'} message={opening?.validation?.balanced?'借贷试算平衡':'借贷试算待校验'} description={`借方 ${money(opening?.validation?.debit)} / 贷方 ${money(opening?.validation?.credit)}`}/><Alert showIcon type={opening?.validation?.equationBalanced?'success':'warning'} message={opening?.validation?.equationBalanced?'会计恒等式成立':'会计恒等式待校验'} description={`资产 ${money(opening?.validation?.assets)} / 负债和权益 ${money(opening?.validation?.liabilitiesAndEquity)}`}/></div><Table rowKey={(r:any)=>r.account.id} pagination={{pageSize:20}} scroll={{x:720}} dataSource={(opening?.rows||[]).filter((r:any)=>Number(r.debitAmount)||Number(r.creditAmount))} locale={{emptyText:<Empty description="下载模板填写后导入，系统会先校验再保存"/>}} columns={[{title:'科目编码',dataIndex:['account','code']},{title:'科目名称',dataIndex:['account','name']},{title:'期初借方',dataIndex:'debitAmount',align:'right' as const,render:money},{title:'期初贷方',dataIndex:'creditAmount',align:'right' as const,render:money}]}/></Card>},
      {key:'vouchers',label:<span><AuditOutlined/> 智能凭证</span>,children:<Card className="accounting-card" title={`${period} 凭证中心`} extra={<Space wrap><Button icon={<ReloadOutlined/>} disabled={periodClosed} onClick={syncSources}>同步业务单据</Button><Button type="primary" icon={<PlusOutlined/>} disabled={periodClosed} onClick={()=>openVoucher()}>新增凭证</Button></Space>}><Alert showIcon type="info" message="流水保存后自动生成草稿凭证" description="草稿可人工调整；复核后才能过账。每次修改、复核、过账和取消过账都有历史记录。"/><Table loading={loading} rowKey="id" dataSource={vouchers} columns={voucherColumns} scroll={{x:1200}} pagination={{pageSize:20}}/></Card>},
      {key:'ledger',label:<span><BookOutlined/> 账簿</span>,children:<Card className="accounting-card" title={`${period} 账簿中心`} extra={<Tag color={ledger?.validation.debit===ledger?.validation.credit?'green':'red'}>本期发生额借贷{ledger?.validation.debit===ledger?.validation.credit?'平衡':'不平'}</Tag>}><Tabs items={[{key:'balance',label:'科目余额表',children:<Table rowKey={(r:LedgerRow)=>r.account.id} dataSource={ledger?.rows||[]} columns={ledgerColumns} scroll={{x:1060}} pagination={{pageSize:30}} summary={()=>ledger?.rows.length?<Table.Summary.Row><Table.Summary.Cell index={0} colSpan={4}><strong>本期发生额合计</strong></Table.Summary.Cell><Table.Summary.Cell index={4} align="right"><strong>{money(ledger.validation.debit)}</strong></Table.Summary.Cell><Table.Summary.Cell index={5} align="right"><strong>{money(ledger.validation.credit)}</strong></Table.Summary.Cell><Table.Summary.Cell index={6}/><Table.Summary.Cell index={7}/></Table.Summary.Row>:null}/>},{key:'journal',label:'序时账 / 明细账',children:<Table rowKey="id" dataSource={ledgerDetail?.entries||[]} scroll={{x:1050}} pagination={{pageSize:30}} columns={[{title:'日期',dataIndex:['voucher','voucherDate'],width:110},{title:'凭证号',dataIndex:['voucher','voucherNo'],width:110},{title:'科目',render:(_:unknown,r:LedgerEntry)=>`${r.account.code} ${r.account.name}`,minWidth:210},{title:'摘要',dataIndex:'summary',minWidth:220},{title:'项目',dataIndex:'projectName',render:(v:string|null)=>v||'—'},{title:'往来单位',dataIndex:'counterpartyName',render:(v:string|null)=>v||'—'},{title:'借方',dataIndex:'debit',align:'right' as const,render:money},{title:'贷方',dataIndex:'credit',align:'right' as const,render:money}]}/>},{key:'project',label:'项目辅助账',children:<Table rowKey="name" dataSource={ledgerDetail?.projectSummary||[]} pagination={false} columns={[{title:'项目',dataIndex:'name'},{title:'分录数',dataIndex:'entries'},{title:'借方发生额',dataIndex:'debit',align:'right' as const,render:money},{title:'贷方发生额',dataIndex:'credit',align:'right' as const,render:money}]}/>} ,{key:'counterparty',label:'往来账',children:<Table rowKey="name" dataSource={ledgerDetail?.counterpartySummary||[]} pagination={false} locale={{emptyText:<Empty description="在凭证分录填写往来单位后，这里会自动汇总"/>}} columns={[{title:'往来单位',dataIndex:'name'},{title:'分录数',dataIndex:'entries'},{title:'借方发生额',dataIndex:'debit',align:'right' as const,render:money},{title:'贷方发生额',dataIndex:'credit',align:'right' as const,render:money}]}/>} ]}/></Card>},
      {key:'reports',label:<span><FileTextOutlined/> 财务报表</span>,children:<div className="report-layout"><Card className="report-card" title="资产负债表" extra={reports?.balanceSheet.balanced?<Tag color="green" icon={<CheckCircleOutlined/>}>平衡</Tag>:<Tag color="red" icon={<CloseCircleOutlined/>}>不平衡</Tag>}><div className="report-line"><span>资产合计</span><strong>¥{money(reports?.balanceSheet.assets)}</strong></div><div className="report-line"><span>负债合计</span><strong>¥{money(reports?.balanceSheet.liabilities)}</strong></div><div className="report-line"><span>所有者权益合计</span><strong>¥{money(reports?.balanceSheet.equity)}</strong></div><div className="report-total"><span>负债和所有者权益合计</span><strong>¥{money(reports?.balanceSheet.liabilitiesAndEquity)}</strong></div></Card><Card className="report-card" title="利润表"><div className="report-line"><span>营业收入</span><strong>¥{money(reports?.profitStatement.operatingRevenue)}</strong></div><div className="report-line"><span>营业成本及费用</span><strong>¥{money(reports?.profitStatement.operatingCosts)}</strong></div><div className="report-total"><span>净利润</span><strong>¥{money(reports?.profitStatement.netProfit)}</strong></div></Card><Alert className="report-note" showIcon type="info" message="上海报送档案已启用" description="内部按月结账；对外原则上按季度、年度报送，实际表种以企业在电子税务局备案自动带出的“财务报表报送小类”为准。现金流量表、附注和电子税务局导入文件将在完整现金流项目映射后开放。" action={<Button icon={<DownloadOutlined/>} onClick={downloadReports}>导出核对 Excel</Button>}/></div>},
      {key:'closing',label:<span><LockOutlined/> 月末处理</span>,children:<Card className="accounting-card month-end-card"><div className="month-end-heading"><div className={periodClosed?'period-seal closed':'period-seal'}><LockOutlined/><span>{period}</span><b>{periodClosed?'已结账':'待结账'}</b></div><div><h3>月末关账检查</h3><p>结账会锁定本期凭证与期初数据。系统先检查所有凭证均已过账、资产负债表平衡，再允许完成。</p></div></div><div className="month-end-checks"><div><CheckCircleOutlined/><span>凭证借贷平衡</span></div><div className={(overview?.voucherCounts.draft||overview?.voucherCounts.reviewed)?'pending':''}><CheckCircleOutlined/><span>无待复核、待过账凭证</span></div><div className={reports?.balanceSheet.balanced?'':'pending'}><CheckCircleOutlined/><span>资产等于负债和所有者权益</span></div><div className="pending"><CheckCircleOutlined/><span>折旧、摊销、工资税费需先配置来源数据</span></div></div><div className="month-end-actions"><Space wrap>{!periodClosed&&<Button icon={<AuditOutlined/>} onClick={generateProfitClosing}>生成损益结转凭证</Button>}{periodClosed?<Popconfirm title="确认反结账？" description="账期会重新开放，操作将保留记录。" onConfirm={()=>closePeriod(true)}><Button danger icon={<UnlockOutlined/>}>反结账</Button></Popconfirm>:<Popconfirm title={`确认结账 ${period}？`} description="完成检查后，本期数据将锁定。" onConfirm={()=>closePeriod(false)}><Button type="primary" icon={<LockOutlined/>}>执行结账检查并结账</Button></Popconfirm>}</Space></div></Card>},
    ]}/>

    <Modal title="新增明细科目" open={accountOpen} onCancel={()=>setAccountOpen(false)} footer={null} destroyOnClose><Form form={accountForm} layout="vertical" onFinish={createAccount}><Form.Item label="上级科目" name="parentId" rules={[{required:true,message:'请选择上级科目'}]}><Select showSearch optionFilterProp="label" options={accounts.filter(a=>a.isActive).map(a=>({value:a.id,label:`${a.code} ${a.name}`}))}/></Form.Item><Form.Item label="明细科目编码" name="code" rules={[{required:true,message:'请填写明细科目编码'}]} extra="编码必须以上级科目编码开头，例如 100201。"><Input maxLength={32}/></Form.Item><Form.Item label="明细科目名称" name="name" rules={[{required:true,message:'请填写明细科目名称'}]}><Input maxLength={120}/></Form.Item><div className="modal-actions"><Button onClick={()=>setAccountOpen(false)}>取消</Button><Button type="primary" htmlType="submit">新增科目</Button></div></Form></Modal>
    <Modal title={editing?`修改凭证 ${editing.voucherNo}`:'新增记账凭证'} open={voucherOpen} onCancel={()=>setVoucherOpen(false)} footer={null} width={1000} destroyOnClose><Form form={voucherForm} layout="vertical" onFinish={saveVoucher}><div className="voucher-head-fields"><Form.Item label="凭证日期" name="voucherDate" rules={[{required:true,message:'请选择日期'}]}><DatePicker/></Form.Item><Form.Item label="凭证摘要" name="summary" rules={[{required:true,message:'请填写摘要'}]}><Input maxLength={500}/></Form.Item></div><Form.List name="lines">{(fields,{add,remove})=><><div className="voucher-line-header"><span>科目</span><span>摘要</span><span>往来单位</span><span>借方金额</span><span>贷方金额</span><span/></div>{fields.map((field,index)=><div className="voucher-line-form" key={field.key}><Form.Item name={[field.name,'accountId']} rules={[{required:true,message:'请选择科目'}]}><Select showSearch optionFilterProp="label" placeholder="选择末级科目" options={postingAccounts.map(a=>({value:a.id,label:`${a.code} ${a.name}`}))}/></Form.Item><Form.Item name={[field.name,'summary']}><Input placeholder="分录摘要"/></Form.Item><Form.Item name={[field.name,'counterpartyName']}><Input placeholder="客户 / 供应商"/></Form.Item><Form.Item name={[field.name,'debit']}><InputNumber min={0} precision={2} placeholder="0.00"/></Form.Item><Form.Item name={[field.name,'credit']}><InputNumber min={0} precision={2} placeholder="0.00"/></Form.Item><Button danger type="text" disabled={fields.length<=2} onClick={()=>remove(index)}>删除</Button></div>)}<Button block type="dashed" icon={<PlusOutlined/>} onClick={()=>add({summary:voucherForm.getFieldValue('summary')})}>增加分录</Button></>}</Form.List><div className="modal-actions"><Button onClick={()=>setVoucherOpen(false)}>取消</Button><Button type="primary" htmlType="submit">保存为草稿</Button></div></Form></Modal>
    <Modal title="凭证修改记录" open={history!==null} onCancel={()=>setHistory(null)} footer={<Button onClick={()=>setHistory(null)}>关闭</Button>}><div className="audit-timeline">{history?.map(item=><div key={item.id}><i/><section><strong>{item.description}</strong><time>{dayjs(item.createdAt).format('YYYY-MM-DD HH:mm:ss')}</time>{item.snapshot&&<p>状态/版本：{item.snapshot.status||item.snapshot.revision||'—'}</p>}</section></div>)}{history?.length===0&&<Empty description="暂无修改记录"/>}</div></Modal>
  </div>;
}
