packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@nestjs/core': true
  bcrypt: false
  esbuild: true
supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - x64
  libc:
    - current
    - glibc
